---
name: "CITestsClang"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  citests:
    name: CI-Tests-Clang
    runs-on: ubuntu-latest
    env:
        CC: clang
        CXX: clang++

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2
          submodules: 'recursive'

      - name: Building picoquic
        run: |
          sudo apt-get install clangd
          sudo apt-get install -y libssl-dev
          echo $CC
          echo $CXX
          $CC --version
          ./ci/build_picotls.sh
          cmake -S . -B build
          cmake --build build

      - name: Perform Unit Tests
        run: |
            ulimit -c unlimited -S
            cd build
            ./picoquic_ct -S .. -n -r && QUICRESULT=$?
            ./picohttp_ct -S .. -n -r -x http_corrupt && HTTPRESULT=$?
            if [[ ${QUICRESULT} == 0 ]] && [[ ${HTTPRESULT} == 0 ]]; then exit 0; fi;
            exit 1
